name: NuGet Release

on:
  push:
    branches: 
      - master

jobs:
  publish:

    runs-on: ubuntu-latest
    name: Publish NuGet Packages
    
    steps:
      - uses: actions/checkout@v2
          
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.0.0
        with:
          version: 3.1.100
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
      
      - name: Build Entire Solution
        run: dotnet build --configuration Release
      
      - name: Pack Solution
        run: dotnet pack --configuration Release
      
      - name: Publish Sanchez.Markdown.Symbols
        run: dotnet nuget push Sanchez.Markdown.Symbols/bin/Release/*.nupkg
          
      - name: Publish Sanchez.Markdown.Parser
        run: dotnet nuget push Sanchez.Markdown.Parser/bin/Release/*.nupkg
            
      - name: Publish Sanchez.Markdown.Renderers
        run: dotnet nuget push Sanchez.Markdown.Renderers/bin/Release/*.nupkg
        
      - name: Publish Sanchez.Markdown.Renderers.Blazor
        run: dotnet nuget push Sanchez.Markdown.Renderers/bin/Release/*.nupkg
