name: Unit Testing

on:
  push:
    branches:
      - master

jobs:
  build:
    
    runs-on: ubuntu-latest
    name: Build Application
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.0.0
        with:
          version: 3.1.100
          
      - name: Build Debug Solution
        run: dotnet build
        
      - name: Build Release Solution
        run: dotnet build --configuration Release
